# Generated by Django 5.1 on 2025-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(help_text="Référence de l'article dans le code de la route (ex: 106.4).", max_length=20, unique=True, verbose_name="Code de l'article")),
                ('category', models.CharField(choices=[('CONDUITE', 'Conduite des véhicules et des animaux'), ('USAGE_VOIE', 'Usage des voies ouvertes à la circulation'), ('VEHICULE', 'Equipement des véhicules'), ('ADMINISTRATIF', 'Conditions administratives et documents'), ('PERMIS', 'Permis de conduire'), ('GENERAL', 'Dispositions générales')], max_length=50, verbose_name="Catégorie de l'infraction")),
                ('description', models.TextField(verbose_name="Description de l'infraction")),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amende minimale (Z)')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amende maximale (Z)')),
            ],
            options={
                'verbose_name': 'Infraction',
                'verbose_name_plural': 'Infractions',
                'ordering': ['code_article'],
            },
        ),
    ]
