# Generated by Django 5.1 on 2025-09-24 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_infraction'),
        ('vehicules', '0002_alter_vehicle_owner_alter_vehicle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_amende', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'amende")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant de l'amende (Z)")),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('CONTESTEE', 'Contestée'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=20, verbose_name="Statut de l'amende")),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_limite_paiement', models.DateField(verbose_name='Date limite de paiement')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('lieu_infraction', models.CharField(max_length=200, verbose_name="Lieu de l'infraction")),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email de notification envoyé')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent verbalisateur')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detection', verbose_name='Détection associée')),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.infraction', verbose_name='Infraction commise')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.vehicle', verbose_name='Véhicule en infraction')),
            ],
            options={
                'verbose_name': 'Amende',
                'verbose_name_plural': 'Amendes',
                'ordering': ['-date_emission'],
            },
        ),
    ]
