# Generated by Django 5.1 on 2025-09-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_amende'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amende',
            name='detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.detection', verbose_name='Détection associée'),
        ),
    ]
