# Generated by Django 5.1 on 2025-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_allow_null_detection_in_amende'),
    ]

    operations = [
        migrations.AddField(
            model_name='amende',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='amende',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AlterField(
            model_name='amende',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant de l'amende (Fc)"),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amende maximale (Fc)'),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amende minimale (Fc)'),
        ),
    ]
