# Generated by Django 5.1 on 2025-09-26 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Code agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_agent_codes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_agent_code', to=settings.AUTH_USER_MODEL, verbose_name='Utilisé par')),
            ],
            options={
                'verbose_name': 'Code agent',
                'verbose_name_plural': 'Codes agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
